#!/bin/sh

SYS_PROFILE="/etc/profile"
COMMENT="# added by Ant Installer"


# remove symlinks
rm "/usr/local/bin/ant"
rm "/usr/local/ant"


# remove /etc/profile additions
sed -i "/${COMMENT}/d" "$SYS_PROFILE"


# return successfully
exit 0
