#!/bin/sh

PKG_LOG="$SYNOPKG_PKGDEST/install-ant.log"


# set working dir
cd "$SYNOPKG_PKGDEST"

# fetch JDK
. "$SYNOPKG_PKGDEST/install-ant.sh" 2>&1 | tee "$PKG_LOG"


# make sure that `ant` is working
if [ -x "/usr/local/ant/bin/ant" ]; then
	# display success message
	export ANT_HOME="/usr/local/ant" && "/usr/local/ant/bin/ant" -version 2>&1 | tee "$SYNOPKG_TEMP_LOGFILE"
else
	# display error message
	echo "Ooops, something went wrong... View Log for details." | tee "$SYNOPKG_TEMP_LOGFILE"
fi


# return successfully
exit 0
