#!/bin/sh

SYS_PROFILE="/etc/profile"
COMMENT="# added by Apache Ant"

case "$1" in
	start)
		# add symlinks
		ln -sf "$SYNOPKG_PKGDEST/bin/ant" "/usr/local/bin/ant"
		ln -sf "$SYNOPKG_PKGDEST" "/usr/local/ant"

		# add environment variables to /etc/profile
		if [ `grep -c "$COMMENT" $SYS_PROFILE` == "0" ]; then
			echo "export ANT_HOME=/usr/local/ant      $COMMENT" >> "$SYS_PROFILE"
		fi
		exit 0
	;;

	stop)
		# remove symlinks
		rm "/usr/local/bin/ant"
		rm "/usr/local/ant"

		# remove /etc/profile additions
		sed -i "/${COMMENT}/d" "$SYS_PROFILE"
		exit 0
	;;

	status)
		if [ -x "/usr/local/bin/ant" ] && [ -x "/usr/local/ant/bin/ant" ]; then
			exit 0
		else
			exit 150 # package is broken and should be reinstalled
		fi
	;;

	log)
		exit 0
	;;

	*)
		echo "Usage: $0 {start|stop|status|log}"
		exit 1
	;;
esac
